on: [push]
name: CI
jobs: 
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Wasmer
        uses: wasmerio/setup-wasmer@v2
      - name: Install web assembly tool kit
        run: sudo apt-get install -y wabt
      - uses: haskell-actions/setup@v2
        id: setup
        with:
          ghc-version: '9.6.3'
      - name: Configure
        run: |
          cabal configure
          cabal build all --dry-run
      - name: Restore cached dependencies
        uses: actions/cache/restore@v3
        id: cache
        env:
          key: ghc-${{ steps.setup.outputs.ghc-version }}-cabal-${{ steps.setup.outputs.cabal-version }}
        with:
          path: ${{ steps.setup.outputs.cabal-store }}
          key: ${{ env.key }}-plan-${{ hashFiles('**/plan.json') }}
          restore-keys: ${{ env.key }}-
      - name: Install Deps
        run: |
          cabal build all --only-dependencies
      - name: Save cached dependencies
        uses: actions/cache/save@v3
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.setup.outputs.cabal-store }}
          key: ${{ steps.cache.outputs.cache-primary-key }}
      - name: Build All
        run: cabal build all
      - name: Run tests
        run: cabal run tests
