on: [push]
name: CI
jobs: 
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Wasmer
        uses: wasmerio/setup-wasmer@v2
      - name: Install web assembly tool kit
        run: sudo apt-get install -y wabt
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.6.3'
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path:  ${{ steps.setup.outputs.cabal-store }}
          key: haskell-deps-${{ hashFiles('typed-wasm.cabal') }}
          restore-keys: haskell-deps-
      - name: Configure
        run: |
          cabal configure
          cabal build all --dry-run
      - name: Install Deps
        run: |
          cabal build all --only-dependencies
          cabal test --only-dependencies
      - name: Build All
        run: cabal build all
      - name: Run tests
        run: cabal run tests
